<?php

namespace app\components;

use yii\base\Widget;

class MyWidget extends Widget
{
    public $name;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if ($this->name === null) {
            $this->name = 'guest';
        }

        ob_start();
    }

    public function run()
    {
        // если много html кода необязательно здесь писать все.
        // можем сразу вернуть или подгружать.
        //return $this->render('my', ['name' => $this->name]);
        //return '<h1>Hello, ' . $this->name . '!</h1>';

        $content = ob_get_clean();
        $content = mb_strtoupper($content);
        return $this->render('my', compact('content'));
    }

}